-- V2__seed_stalls.sql
-- Seed sample stalls for testing and demonstration

INSERT INTO stall (code, size, location, price, status, created_at, updated_at) VALUES
-- Hall A - Small Stalls
('A-001', 'SMALL', 'Hall A - North Wing, Row 1', 500.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A-002', 'SMALL', 'Hall A - North Wing, Row 1', 500.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A-003', 'SMALL', 'Hall A - North Wing, Row 2', 500.00, 'HELD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A-004', 'SMALL', 'Hall A - North Wing, Row 2', 500.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A-005', 'SMALL', 'Hall A - South Wing, Row 1', 550.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Hall A - Medium Stalls
('A-101', 'MEDIUM', 'Hall A - Center, Row 1', 1000.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A-102', 'MEDIUM', 'Hall A - Center, Row 1', 1000.00, 'RESERVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A-103', 'MEDIUM', 'Hall A - Center, Row 2', 1050.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A-104', 'MEDIUM', 'Hall A - Center, Row 2', 1050.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A-105', 'MEDIUM', 'Hall A - Center, Row 3', 1000.00, 'HELD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Hall A - Large Stalls
('A-201', 'LARGE', 'Hall A - Premium Zone, Corner 1', 2000.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A-202', 'LARGE', 'Hall A - Premium Zone, Corner 2', 2000.00, 'RESERVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A-203', 'LARGE', 'Hall A - Premium Zone, Center', 2500.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Hall B - Small Stalls
('B-001', 'SMALL', 'Hall B - East Wing, Row 1', 450.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('B-002', 'SMALL', 'Hall B - East Wing, Row 1', 450.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('B-003', 'SMALL', 'Hall B - East Wing, Row 2', 450.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('B-004', 'SMALL', 'Hall B - West Wing, Row 1', 475.00, 'HELD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('B-005', 'SMALL', 'Hall B - West Wing, Row 1', 475.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Hall B - Medium Stalls
('B-101', 'MEDIUM', 'Hall B - Central Area, Row 1', 950.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('B-102', 'MEDIUM', 'Hall B - Central Area, Row 1', 950.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('B-103', 'MEDIUM', 'Hall B - Central Area, Row 2', 975.00, 'RESERVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('B-104', 'MEDIUM', 'Hall B - Central Area, Row 2', 975.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Hall B - Large Stalls
('B-201', 'LARGE', 'Hall B - Exhibition Zone, Front', 1800.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('B-202', 'LARGE', 'Hall B - Exhibition Zone, Front', 1800.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('B-203', 'LARGE', 'Hall B - Exhibition Zone, Rear', 1750.00, 'HELD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Hall C - Small Stalls
('C-001', 'SMALL', 'Hall C - Ground Level, Section 1', 525.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C-002', 'SMALL', 'Hall C - Ground Level, Section 1', 525.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C-003', 'SMALL', 'Hall C - Ground Level, Section 2', 525.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C-004', 'SMALL', 'Hall C - Ground Level, Section 2', 525.00, 'RESERVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Hall C - Medium Stalls
('C-101', 'MEDIUM', 'Hall C - Mezzanine Level, Zone A', 1100.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C-102', 'MEDIUM', 'Hall C - Mezzanine Level, Zone A', 1100.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C-103', 'MEDIUM', 'Hall C - Mezzanine Level, Zone B', 1150.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C-104', 'MEDIUM', 'Hall C - Mezzanine Level, Zone B', 1150.00, 'HELD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Hall C - Large Stalls
('C-201', 'LARGE', 'Hall C - VIP Section, Position 1', 2200.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C-202', 'LARGE', 'Hall C - VIP Section, Position 2', 2200.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C-203', 'LARGE', 'Hall C - VIP Section, Position 3', 2300.00, 'RESERVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Outdoor Area - Large Stalls
('OUT-001', 'LARGE', 'Outdoor Plaza - East Side', 1500.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('OUT-002', 'LARGE', 'Outdoor Plaza - West Side', 1500.00, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('OUT-003', 'LARGE', 'Outdoor Plaza - North Entrance', 1600.00, 'HELD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
